# Generated by Django 2.2.13 on 2020-06-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkmenistan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turkmen',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
