# Generated by Django 2.2.13 on 2020-06-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Government', 'Government'), ('Intergovernmental Organization', 'Intergovernmental Organization'), ('NGO', 'NGO'), ('Company', 'Company'), ('Press', 'Press'), ('Other', 'Other')], default='Government institution', max_length=100)),
                ('country', models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Turkmenistan', 'Turkmenistan'), ('Turkey', 'Turkey'), ('USA', 'USA'), ('UK', 'UK')], default='Select your country', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('position_delegation', models.CharField(choices=[('Head of delegation', ' Head of delegation'), ('Deputy', 'Deputy'), ('Protocol officer', 'Protocol officer'), ('Security', 'Security'), ('Press', 'Press'), ('Other', 'Other')], default='Select your position', max_length=100)),
                ('citizenship', models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Turkmenistan', 'Turkmenistan'), ('Turkey', 'Turkey'), ('USA', 'USA'), ('UK', 'UK')], default='Select your citizenship', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Select your gender', max_length=30)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('passport_image', models.ImageField(upload_to='images/')),
                ('photo', models.ImageField(upload_to='images/')),
                ('passport_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('office_phone', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('email2', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('address', models.CharField(max_length=100)),
                ('means_of_transport', models.CharField(max_length=100)),
                ('arr_date', models.DateField()),
                ('arr_flight_number', models.CharField(max_length=100)),
                ('dep_date', models.DateField()),
                ('dep_flight_number', models.CharField(max_length=100)),
                ('nda_required', models.BooleanField(default=False)),
                ('privacy', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
